### ISSUE TITLE
YahooNews scenario fails frequently 

### ISSUE THREAD

**Issue by rahulchaphalkar** [MicrosoftEdge/BrowserEfficiencyTest#93]
I've observed recently that YahooNews scenario causes the workload to abort quite frequently, the most common exception thrown being related to Timeout:
![yahoo1](https://user-images.githubusercontent.com/15642191/28735260-50e22818-7399-11e7-9486-1b3b8db36634.PNG)

and another exception sometimes being:
![insertbefore](https://user-images.githubusercontent.com/15642191/28735281-60181590-7399-11e7-898f-e73a6ff5931c.PNG)

I'm using windows public build 15063, and the latest web driver available.

**Comment by TychosNose** [comment]
I haven't seen this on the 15063 runs I've done so I'm in the dark on what this could be.
In the first image, the HTTP request to MicrosoftWebDriver.exe appears to be timing out.  By default it is 60 seconds so I suspect something is happening to MicrosoftWebDriver.exe or the Edge content process. Is MicrosoftWebDriver.exe or the Edge tab crashing before this exception is thrown?

In the second image, it looks like the element the yahoo scenario is looking for to insert the javascript is not found. I suspect this is because the page isn't loaded yet? I'm not sure why the page wouldn't be finished loading yet at that point in the test.

**Comment by rahulchaphalkar** [comment]
For me, it kind of varies with the day I run it. Today, its giving the above exceptions around 1 in 10 times, so maybe a bit hard to notice.

**Comment by sooraj77** [comment]
It might be causing because huge page loading time. if you increase the time-out to 120 sec or high it will run without error. This will depends your network and device performance. Increase time-out is a quick method to fix this issue.Change time-out here BrowserEfficiencyTest\BrowserEfficiencyTest\bin\Debuge\workloads.json for yahoo scenario.

**Comment by rahulchaphalkar** [comment]
Thanks for the assistance guys. Closing this issue, don't see it happening anymore.
